version: '3'

services:
    db:
        build:
          context: .
          dockerfile: Dockerfile.db
        environment:
          - POSTGRES_DB=homefamily
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432

    spring:
        build:
            context: .
            dockerfile: Dockerfile.api
        volumes:
            - ./:/var/www/symfony
        ports:
            - 8000:8080
        environment:
          - POSTGRES_DB=homefamily
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres